Feature/update conventional commits
ohpensource/platform-cicd pull request #72
Opened 2022-02-21 09:56 UTC by ohpdrebolo

2022-02-21 10:21 UTC, mmichna approved these changes

2022-02-21 14:00 UTC, lucky-edu requested changes
Show in your commits that this will introduce breaking changes.

2022-02-21 14:01 UTC, lucky-edu requested changes
Test such changes in this repository.

2022-02-21 14:05 UTC, lucky-edu requested changes
![image](https://user-images.githubusercontent.com/88039083/154970228-c9f5f369-56a8-4813-b5c1-e0e26133891d.png)

Conventional commits support the "BREAKING CHANGE" prefix. Do the same in your flow and document it.

2022-02-22 08:25 UTC, ohpdrebolo commented
> ![image](https://user-images.githubusercontent.com/88039083/154970228-c9f5f369-56a8-4813-b5c1-e0e26133891d.png)
> 
> If a user introduces braking changes will need to do so in many lines in the commit message. Is this supported by the semver script?

BREAKING CHANGE: a commit that has a footer BREAKING CHANGE:, or appends a ! after the type/scope.

We are appending ! after type/scope

2022-02-22 08:26 UTC, ohpdrebolo commented
> Show in your commits that this will introduce breaking changes.


I rebased -i.. 


feat(convcomm)!: SPT-209 types scope breaking colon space and subject…
feat(semver)!: SPT-209 semver script read breaking change in differen…

2022-02-22 08:50 UTC, mmichna submitted a review, later dismissed

2022-02-23 15:38 UTC, vscheidegger commented
> > Show in your commits that this will introduce breaking changes.
> 
> I rebased -i..
> 
> feat(convcomm)!: SPT-209 types scope breaking colon space and subject… feat(semver)!: SPT-209 semver script read breaking change in differen…

@ohpdrebolo as your change has not being applied yet, the commit you show here would not work to change the version of this repo (remember, the actions are versioned, but they are **currently versioned** using the **current script**).
You need to add a commit with a "break: {{message}}" to increase the current MAJOR version of the action.

2022-03-15 07:45 UTC, lucky-edu commented
Why is this PR not moving @ohpdrebolo ?

2022-03-27 16:47 UTC, vscheidegger commented
I'm trying to push a commit to add tests, but I don't have enough access. I opened a request on PST Teams channel, as soon as I have it I will update this PR.

2022-04-01 13:38 UTC, vscheidegger commented on README.md
> +#### Types:
Could you say something along the lines of _"The list below represents the default types implemented, but that a different list may be passed as a parameter to the action, in accordance with the Conventional Commits specification."_?

2022-04-01 13:53 UTC, vscheidegger submitted a review, later dismissed

2022-04-01 14:13 UTC, vscheidegger approved these changes

2022-04-01 14:37 UTC, lucky-edu submitted a review, later dismissed

2022-04-01 14:37 UTC, lucky-edu commented on README.md
> +- Commits MUST be prefixed with a type, which consists of a noun, feat, fix, etc., followed by the OPTIONAL scope, OPTIONAL !, and REQUIRED terminal colon and space.
noun? what does it mean?

2022-04-01 14:37 UTC, lucky-edu commented on README.md
> +- Commits MUST be prefixed with a type, which consists of a noun, feat, fix, etc., followed by the OPTIONAL scope, OPTIONAL !, and REQUIRED terminal colon and space.
ah ok, would it make sense to put "... noun (feat, fix, etc., ...)"?

2022-04-01 14:37 UTC, lucky-edu commented on README.md
> +- **break (deprecated)** --> deprecated, you should use **!**. Updates the MAJOR semver number. Used when a breaking changes are introduced in your code. A commit message example could be "_feat!: de
what does deprecated mean?
If it means "not supported", let's just remove from the list.

2022-04-01 14:37 UTC, lucky-edu commented on actions/git/git-tools.js
> +    subject: null,
what is this for?

2022-04-01 14:37 UTC, lucky-edu commented on actions/git/git-tools.js
> +    subject: null,
all null values? why not remove them?

2022-04-01 14:37 UTC, lucky-edu commented on actions/git/logging.js
> +  console.log("\x1b[37m%s\x1b[0m", key, JSON.stringify(value, null, 2));
what is this string for?

2022-04-01 14:37 UTC, lucky-edu commented on actions/git/test/cc-allowed-types.js
> +import { expect } from "chai";
Love to see unit tests :). It's been a while (sadly :( ) !!

2022-04-01 14:40 UTC, lucky-edu commented
Resolve conflicts with main branch

2022-04-01 15:12 UTC, vscheidegger approved these changes

2022-04-01 15:55 UTC, vscheidegger commented on README.md
> +- Commits MUST be prefixed with a type, which consists of a noun, feat, fix, etc., followed by the OPTIONAL scope, OPTIONAL !, and REQUIRED terminal colon and space.
From what I understand Damian copied the text from [Conventional Commits Specification](https://www.conventionalcommits.org/en/v1.0.0/#specification)

2022-04-01 16:15 UTC, vscheidegger commented on .github/workflows/action-tests.yml
> +name: continuous-integration
Renamed

2022-04-01 16:19 UTC, vscheidegger commented on .github/workflows/action-tests.yml
> +  push
ci.yml only runs on pull-request. our unit tests action should run on every push to github

2022-04-01 16:19 UTC, vscheidegger commented on .github/workflows/action-tests.yml
> +jobs:
done :)

2022-04-01 16:20 UTC, vscheidegger commented on README.md
> +- break (deprecated): Deprecated type, you should use **!**. A breaking change commit
Added! :)

2022-04-01 16:28 UTC, vscheidegger commented on README.md
> +- **break (deprecated)** --> deprecated, you should use **!**. Updates the MAJOR semver number. Used when a breaking changes are introduced in your code. A commit message example could be "_feat!: de
We added to continue supporting the teams that are using it...
The type itself is not wrong, although the convention is clear about the usage of the exclamation mark for breaking changes.

2022-04-01 16:29 UTC, vscheidegger commented on actions/git/logging.js
> +  console.log("\x1b[37m%s\x1b[0m", key, JSON.stringify(value, null, 2));
This is to add color to the console output

2022-04-06 10:43 UTC, vscheidegger approved these changes

2022-04-06 10:54 UTC, vscheidegger submitted a review, later dismissed

2022-04-06 10:54 UTC, vscheidegger commented on .github/workflows/action-tests.yml
> +  push
The possibility of having a PR that does not run the test on the push is remote, anyway we [added a separate task on our JIRA](https://ohpen.atlassian.net/browse/SPT-261) to add this to the CI in the future

2022-04-06 10:58 UTC, vscheidegger commented
> Can you do an integration test with (at least) the happy pathS? To do so just consume the actions directly from the branch this PR comes from.
> 
> Example: If previously I was using an action like this https://github.com/ohpen/platform-template-serverless-terraform-dotnet/blob/da4a0f6d14bda91f788fd1d2d7d30bfda2b673e2/.github/workflows/ci.yml#L28 You can change the version by your branch name and consume your action.
> 
> important: Make sure to do the same with https://github.com/ohpen/platform-template-serverless-terraform-dotnet/blob/da4a0f6d14bda91f788fd1d2d7d30bfda2b673e2/.github/workflows/cd.yml#L31 to you do the full integration test.

Integration tests done in:
https://github.com/emartinezohpen/platform-cicd-test/actions

The successful tests are the ones after the action "continuous-integration-test #7"

![image](https://user-images.githubusercontent.com/92516894/161960239-396673fb-11fb-4617-89b1-326b608c3ab2.png)

2022-04-06 11:56 UTC, vscheidegger approved these changes

2022-04-07 12:39 UTC, lucky-edu commented
I did some integration testing and found things that I don't understand.
https://github.com/ohpen/platform-repository-for-testing/pull/1/checks

- Besides the problems, could we make the tools to analyze all commits and provide for all of them feedback? :) 
- What am I missing in my commits? All of them seem to follow conventional commits 🤔 ...

2022-04-07 12:39 UTC, lucky-edu requested changes

2022-04-07 15:16 UTC, vscheidegger commented on .github/workflows/action-tests.yml
> +jobs:
Of course we considered.
The idea of the push is to fail faster, so our tests are run every time there is a change (actually a pushed commit) on the action folder, even before the PR is submitted.
Adding it also to the PR would only cover a specific case (and probably not very plausible one), so decided not to bother with it now.
We added a ticket to our backlog though [SPT-261](https://ohpen.atlassian.net/browse/SPT-261)

2022-04-08 08:51 UTC, vscheidegger approved these changes

2022-04-08 08:51 UTC, vscheidegger commented on actions/git/git-tools.js
> +    subject: null,
This fields are the representation of [conventional commit fields from the specification](https://www.conventionalcommits.org/en/v1.0.0/)

2022-04-08 08:53 UTC, vscheidegger commented on actions/git/git-tools.js
> +    subject: null,
They are null on the definition, they didn't need to be defined, but they were to make it clear that we expect them to be filled (that's what is being done in line 64).

2022-04-08 08:56 UTC, vscheidegger commented on .github/workflows/action-tests.yml
> +    - 'actions/**'
This is the action that executes the test on the actions we changed. It is executed every time there is a push that changes any items in the "actions" folder.

2022-04-08 08:57 UTC, vscheidegger commented on .github/workflows/action-tests.yml
> +        uses: actions/cache@v2
The caching makes the npm install runs faster if the cache key is found in the runner.

2022-04-08 08:58 UTC, vscheidegger commented on .github/workflows/ci.yml
> +        run: node ./actions/git/ensure-conventional-commits/ensure-conventional-commits.js $GITHUB_BASE_REF $GITHUB_HEAD_REF
As we added a npm module (ES6) we organized the scripts for the action inside this folder.

2022-04-08 08:58 UTC, vscheidegger commented on .gitignore
> +**/node_modules
node_modules were only ignored in the root folder. It would not ignore the node_modules that are specific for the actions.

2022-04-08 09:02 UTC, vscheidegger commented on actions/git/ensure-conventional-commits/action.yml
> +    required: false
New optional attribute added to the action, this allows each team to define their own set of types - [as per the conventional commits specification](https://www.conventionalcommits.org/en/v1.0.0/)

2022-04-08 09:04 UTC, emartinezohpen commented on actions/git/ensure-conventional-commits/action.yml
> +    - run: node ${{ github.action_path }}/ensure-conventional-commits.js ${{ inputs.base-branch }} ${{ inputs.pr-branch }} ${{ inputs.allowed-types }}
As we added a npm module (ES6) we organized the scripts for the action inside this folder.

2022-04-08 09:07 UTC, vscheidegger commented on actions/git/ensure-conventional-commits/constants.js
> +  /(?<type>^[a-z]+)(?<scope>\([a-z,\-]+\))?(?<breaking>!)?(?<colon>:{1})(?<space> {1})(?<subject>.*)/;
Right now the allowed scopes have to be in accordance with the scope regex from above: [a-z,\-]
This means that the valid scopes can only have lower case (a-z) and dashes (-).

2022-04-08 09:07 UTC, vscheidegger commented on actions/git/ensure-conventional-commits/constants.js
> +  /(?<type>^[a-z]+)(?<scope>\([a-z,\-]+\))?(?<breaking>!)?(?<colon>:{1})(?<space> {1})(?<subject>.*)/;
This can be enhanced in a future ticket

2022-04-08 09:08 UTC, vscheidegger commented on actions/git/ensure-conventional-commits/constants.js
> +export const fixType = "fix";
Built-in types are the commit types that are always accepted, according to [the specification](https://www.conventionalcommits.org/en/v1.0.0/)

2022-04-08 09:09 UTC, emartinezohpen commented on actions/git/ensure-conventional-commits/constants.js
> +  /(?<type>^[a-z]+)(?<scope>\([a-z,\-]+\))?(?<breaking>!)?(?<colon>:{1})(?<space> {1})(?<subject>.*)/;
The first conventional commit regex with scopes only allow scopes with lowercase letters and dashes.

2022-04-08 09:10 UTC, vscheidegger commented on actions/git/ensure-conventional-commits/ensure-conventional-commits.js
> +const allowedTypes = getAllowedTypes(types);
This method gets the final list of allowed types, between what was informed (if none was informed - it will get the organization default) and the builtin types from the spec

2022-04-08 09:15 UTC, emartinezohpen commented on actions/git/generate-version-and-release-notes.js
> +                        : process.argv[3];
When argv[3] does not exist we set version prefix as empty in order to avoid tags like undefined0.0.1.

2022-04-08 09:29 UTC, emartinezohpen approved these changes

2022-04-08 10:06 UTC, bernatduran approved these changes
I left a few comments that would be nice to contemplates, but the code seems to be working as is.

2022-04-08 10:17 UTC, vscheidegger commented on .github/workflows/action-tests.yml
> +        run: npm ci
I opened the following ticket to analyze/enhance the caching feature:
https://ohpen.atlassian.net/browse/SPT-279

2022-04-08 10:21 UTC, vscheidegger commented on README.md
>  :warning: Attention! If you set your action to work with 3 numbers, these prefixes will update the PATCH number.
SPT-280

2022-04-08 10:25 UTC, vscheidegger commented on actions/git/ensure-conventional-commits/action.yml
>        shell: bash
As it was already running as a composite - this enhancement was not the goal of this PR.
I created a separate task to analyze it as well.

2022-04-08 10:29 UTC, vscheidegger commented on actions/git/ensure-conventional-commits/action.yml
>        shell: bash
SPT-281 - for changing the runtime
SPT-282 - for changing how we receive the parameters

2022-04-11 21:02 UTC, vscheidegger commented on actions/git/test/cc-check-commits.js
> +    "fix(shell): expect allowed and not allowed commits",
Hey @cangulomascarell is there any problem with the test above?

2022-04-19 08:25 UTC, cangulomascarell commented
The GH action for generate-version-and-release-notes has been migrated to this repo:
https://github.com/ohpensource/generate-version-and-release-notes-gh-action

We have included the features in this PR such as support exclamation mark and custom conventional commits. Please check the readme at that repo.

2022-04-19 08:25 UTC, closed without merging